config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers, shallow: true do
      get :accept, on: :member
    end
  end
  root to: "questions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :body, :question_id, :user_id, presence: true

  default_scope { order(accepted: :desc) }

  def mark_as_accepted
    Answer.transaction do
      question.answers.update_all(accepted:false)
      raise ActiveRecord::Rollback unless question.answers.where(accepted: true).first.nil?
      update!(accepted:true)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user
  validates :title, :body, :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def author_of?(object)
    object.user_id == id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :update]
  before_action :set_answer, only: [:update, :destroy, :accept]

  def create
    @question = Question.find(params[:question_id])    
    @answer = @question.answers.create(answer_params.merge(user: current_user))
  end

  def update
    @answer.update(answer_params) if current_user.author_of?(@answer)
    @question = @answer.question
  end

  def destroy
    @answer.destroy if current_user.author_of?(@answer)
  end

  def accept
    @question = @answer.question
    @answer.mark_as_accepted if current_user.author_of?(@question)
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.build
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to @question
    else
      flash[:notice] = "The form must not be empty"
      render :new
    end
  end

  def update
    @question.update(question_params) if current_user.author_of?(@question)
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy 
      redirect_to questions_path
      flash[:notice] = 'Your question successfully deleted.'
    else
      redirect_to questions_path, error: 'You can delete only your question'
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title,:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  = div_for(answer) do
    p
    .answer-body = answer.body
    p
    - if user_signed_in? && current_user.author_of?(answer)
      p
      = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
      p
        = form_for answer, remote: true, html: {id: "edit-answer-#{answer.id}"} do |f|
          = f.label :body, "Answer"
          = f.text_area :body
          = f.submit 'Save'
      = link_to 'Delete answer', answer, method: :delete, remote: true, data: { confirm: "Delete your answer?" }
      br
    - if user_signed_in? && current_user.author_of?(answer.question)  
      - if answer.accepted?
        = link_to('Accepted', accept_answer_path(answer), class: 'accepted-link', remote: true)
      - else
        = link_to('Accept', accept_answer_path(answer), class: 'accept-link', remote: true)
    - elsif answer.accepted?
      = 'Accepted'

app/views/answers/accept.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').html("<%= j render @question.answers %>")
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('.new_answer').find('textarea').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answer_' + '<%= @answer.id %>').remove();
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answer_'+'<%= @answer.id %>').find('.answer-body').html('<%= @answer.body %>');
  $('form#edit-answer-' + <%= @answer.id %>).hide();
  $('#answer_' + '<%= @answer.id %>').find('.edit-answer-link').show();
<% end %>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Blood"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Blood
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              - if user_signed_in?
                li= link_to "Sign out", destroy_user_session_path, method: :delete
              - else
                li= link_to "Sign in", new_user_session_path
                li= link_to "Sign up", new_user_registration_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        
      footer
        p &copy; Company 2016

app/views/questions/_answers.html.slim
h2 Answers:
= render @question.answers

app/views/questions/index.html.slim
h1 Questions list:
- @questions.each do |question|
  ul
    li= link_to question.title, question
end
p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Post your question'
p
= link_to 'Back', questions_path

app/views/questions/show.html.slim
= div_for(@question) do
  .question_title = @question.title
  .question_body = @question.body

  - if user_signed_in? && current_user.author_of?(@question)
    p
    = form_for @question, remote: true, html: {id: "edit-question-#{@question.id}"} do |f|
      .question-errors
      = f.label :title
      = f.text_field :title
      = f.label :body
      = f.text_area :body
      = f.submit 'Save'
    p
    = link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: @question.id }
    p
    = link_to 'Delete question', @question, method: :delete, data: { confirm: "Are you sure" } 


.answers
  = render "answers"

- if user_signed_in?
  h3 Create your answer:
  = form_for [@question,@answer], remote: true do |f|
    = f.label :body, "Answer"
    .answer-errors
    = f.text_area :body
    = f.submit 'Post your answer'
- else 
  h4 Please sign_in/sign_up

p
= link_to 'Back', questions_path

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<%= j message %>');
  <% end %>
<% else %>
    $('#question_' + '<%= @question.id %>').find('.question_title').html('<%= @question.title %>');
    $('#question_' + '<%= @question.id %>').find('.question_body').html('<%= @question.body %>');
    $('form#edit-question-' + <%= @question.id %>).hide();
    $('#question_' + '<%= @question.id %>').find('.edit-question-link').show();
<% end %>